namespace Week14.Audio
{
    /// <summary>
    /// 게임 코드는 재생 위치만 알리고, 실제 Sound ID는 SoundLibrary에서 연결합니다.
    /// </summary>
    public enum SoundEvent
    {
        UI_ButtonClick,
        UI_Hover,
        UI_SceneTransition,
        UI_TitleStart,
        UI_PauseOpen,
        UI_PauseClose,
        UI_ChallengeRewardPoint,
        UI_LobbyChallengeResult,
        UI_LobbyLoadoutEquip,
        UI_LobbyLoadoutPurchase,
        UI_LobbyPanelShow,
        UI_LobbyPanelHide,
        UI_ResultPanelPopup,
        UI_IntroPlayerWalk,

        Dialogue_TalkERIS,
        Dialogue_TalkLeeOn,
        Dialogue_TalkDad,
        Tutorial_Dialogue,
        Tutorial_ObjectiveComplete,
        Tutorial_TrainingEnemyRaise,
        Tutorial_TrainingEnemyNormalAttack,
        Tutorial_TrainingEnemyRadialAttack,

        Intro_ZoomIn,
        Intro_Set,
        Intro_Shutter,

        Player_BaseballBatCharge,
        Player_BaseballBatSwing,
        Player_BaseballBatHit,
        Player_SniperCharge,
        Player_BayonetSlash,
        Player_RailgunLowFire,
        Player_RailgunFullFire,
        Player_NormalShot,
        Player_PowerShot,
        Player_ShotgunFire,
        Player_SniperFire,
        Player_BulletLoss,
        Player_BulletRestore,
        Player_Parry,
        Player_ExecutionStart,
        Player_DeathDetected,
        Player_DeathSequence,

        Skill_Roll,
        Skill_TimeSlow,
        Skill_CloneAttack,
        Skill_DamageBoost,
        Skill_Emergency,
        Skill_Magnet,
        Skill_Parrying,

        Boss_CreateParrySuppressionBait,
        Boss_Step,
        Boss_BeforeDash,
        Boss_CantParryingShot,
        Boss_ProjectileFire,
        Boss_ProjectileLaunch,
        Boss_AreaWindup,
        Boss_AreaExplosion,
        Boss_MoveComplete,
        Boss_ParryBombSpawn,
        Boss_ChargedProjectileLaunch,
        Boss_SplitImminent,
        Boss_CustomCue,

        Hog_MachinegunCharge,
        Hog_Death,

        Muscle_LineFire,
        Muscle_Death,

        Conductor_Draw,
        Conductor_DrawComplete,
        Conductor_DroneIdle,
        Conductor_PlaceStaff,
        Conductor_Fire,
        Conductor_Launch,
        Conductor_FinalFire,
        Conductor_FinalLaunch,
        Conductor_Death,

        Assassin_Stealth,
        Assassin_Mine,
        Assassin_Fire,
        Assassin_Launch,
        Assassin_ExecutionImage,
        Assassin_Death,

        Hacker_Walk,
        Hacker_Slash,
        Hacker_Lift,
        Hacker_Slam,
        Hacker_SlashMiss,
        Hacker_SniperCharge,
        Hacker_SniperShot,
        Hacker_ChargeDash,
        Hacker_DropWeapon,
        Hacker_OrbitSweep,
        Hacker_WireNode,
        Hacker_BeforeAttack,
        Hacker_FireWire,
        Hacker_WireFlight,
        Hacker_WireConnect,
        Hacker_Hologram,
        Hacker_Fire,
        Hacker_Launch,
        Hacker_ExecutionImage,
        Hacker_Death,

        Arsonist_CircleFire,
        Arsonist_CircleLaunch,
        Arsonist_AttackFire,
        Arsonist_AttackLaunch,
        Arsonist_MinionFire,
        Arsonist_MinionLaunch,

        Execution_HogPreParry,
        Execution_HogAimCharge,
        Execution_MusclePreParry,
        Execution_MuscleAimCharge,
        Execution_ConductorPreParry,
        Execution_ConductorAimCharge,
        Execution_AssassinAimCharge,
        Execution_HackerAimCharge,
        Execution_CommonCue,
        Execution_CueAfterLetterbox,
        Execution_CueFlourishStart,
        Execution_CueFlourishShot,
        Execution_CueBeforePowerShot,
        Execution_CuePowerShot,
        Execution_CueAfterImpact,
        Execution_CueSequenceEnd,

        Projectile_ParryTimedBurst
    }

}
